version: "3"
services:
  sldbLi:
    command: perl sldbLi.pl etc/sldbLi.conf
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: sldbLi
      SLDBLI_CONF: sldbLi%lobbyLogin:${LOBBY_LOGIN} lobbyPassword:${LOBBY_PASSWORD} lobbyHost:${LOBBY_HOST} lobbyPort:${LOBBY_PORT} sldb:${SLDB_DB_USER}/${SLDB_DB_PASSWORD}@${SLDB_DB_DATABASE}
    depends_on:
      - sldb-db
      - slMonitor
      - ratingEngine
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - sldb-log:/sldb/log

  slMonitor:
    command: perl slMonitor.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: slMonitor
      SLMONITOR_CONF: slMonitor%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} lobbyAdminIds:${SLMONITOR_ADMIN_IDS} lobbyHost:${LOBBY_HOST} lobbyPassword:${SLMONITOR_LOBBY_PASSWORD} logFile:${SLMONITOR_LOGFILE} logPvDir:${SLMONITOR_PVLOGDIR}
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  ratingEngine:
    command: perl ratingEngine.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: ratingEngine
      RATINGENGINE_CONF: ratingEngine%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} logFile:${RATINGENGINE_LOGFILE}
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  xmlRpc:
    command: perl xmlRpc.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: xmlRpc
      XMLRPC_CONF: xmlRpc%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} listenAddr:${XMLRPC_LISTEN_ADDR} listenPort:${XMLRPC_LISTEN_PORT} logFile:${XMLRPC_LOGFILE}#xmlRpc.users%${XMLRPC_USERS}
    ports:
      - 8300
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  sldb-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: sldb-db
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - sldb-db:/var/lib/mysql
    restart: always
volumes:
  sldb-db:
  sldb-log:
