version: "3"
services:
  sldbLi:
    command: perl sldbLi.pl etc/sldbLi.conf
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: sldbLi
      SLDBLI_CONF: sldbLi%lobbyLogin:${LOBBY_LOGIN} lobbyPassword:${LOBBY_PASSWORD} lobbyHost:${LOBBY_HOST} lobbyPort:${LOBBY_PORT} sldb:${SLDB_DB_USER}/${SLDB_DB_PASSWORD}@${SLDB_DB_DATABASE}
      USERS_CONF: >
        <accountId1>(<botOwner>)::::::|140\n
        <accountId2>(<botAdmin>)::::::|130\n
        <accountId3>(<botOperator>)::::::|120\n
        ::::1::|110\n
        :::7:::|80\n
        :::6:::|70\n
        :::5:::|60\n
        :::4:::|50\n
        :::3:::|40\n
        :::2:::|30\n
        :::1:::|20\n
        :::0:::|10
      LEVELS_CONF: >
        140|Bot owner\n
        130|Bot Admin\n
        120|Bot Operator\n
        110|Spring lobby moderator\n
        100|Trusted user\n
        80|Ghost\n
        70|Veteran\n
        60|Highly experienced player\n
        50|Experienced player\n
        40|Above average player\n
        30|Average player\n
        20|Beginner\n
        10|Newbie
      COMMANDS_CONF: >
        [adminEvents]\n
        |130\n
        \n
        [banList]\n
        |120\n
        \n
        [checkIps]\n
        |120\n
        \n
        [checkProbSmurfs]\n
        |120\n
        \n
        [checkUserIps]\n
        |120\n
        \n
        [#getSkill]\n
        |0\n
        \n
        [help]\n
        |0\n
        \n
        [helpAll]\n
        |0\n
        \n
        [ipWhois]\n
        |120\n
        \n
        [joinAcc]\n
        |130\n
        \n
        [leaderboard]\n
        |10\n
        \n
        [notSmurf]\n
        |130\n
        \n
        [quit]\n
        |140\n
        \n
        [ranking]\n
        |10\n
        \n
        [reloadConf]\n
        |140\n
        \n
        [rerate]\n
        |140\n
        \n
        [restart]\n
        |110\n
        \n
        [searchUser]\n
        |120\n
        \n
        [sendLobby]\n
        |140\n
        \n
        [set]\n
        |10\n
        \n
        [setBanList]\n
        |120\n
        \n
        [setName]\n
        |130\n
        \n
        [setStartSkill]\n
        |130\n
        \n
        [showStartSkills]\n
        |120\n
        \n
        [skillGraph]\n
        |10\n
        \n
        [splitAcc]\n
        |130\n
        \n
        [topSkill]\n
        |120\n
        \n
        [uWhois]\n
        |120\n
        \n
        [version]\n
        |0\n
        \n
        [whois]\n
        |120\n
    depends_on:
      - sldb-db
      - slMonitor
      - ratingEngine
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - sldb-log:/sldb/log

  slMonitor:
    command: perl slMonitor.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: slMonitor
      SLMONITOR_CONF: slMonitor%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} lobbyAdminIds:${SLMONITOR_ADMIN_IDS} lobbyHost:${LOBBY_HOST} lobbyPassword:${SLMONITOR_LOBBY_PASSWORD} logFile:${SLMONITOR_LOGFILE} logPvDir:${SLMONITOR_PVLOGDIR}
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  ratingEngine:
    command: perl ratingEngine.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: ratingEngine
      RATINGENGINE_CONF: ratingEngine%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} logFile:${RATINGENGINE_LOGFILE}
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  xmlRpc:
    command: perl xmlRpc.pl
    image: badosu/sldb:latest
    environment:
      COMPONENT_NAME: xmlRpc
      XMLRPC_CONF: xmlRpc%dbLogin:${SLDB_DB_USER} dbName:${SLDB_DB_DATABASE} dbPwd:${SLDB_DB_PASSWORD} listenAddr:${XMLRPC_LISTEN_ADDR} listenPort:${XMLRPC_LISTEN_PORT} logFile:${XMLRPC_LOGFILE}#xmlRpc.users%${XMLRPC_USERS}
    ports:
      - 8300
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - sldb-db
    volumes:
      - sldb-log:/sldb/log

  sldb-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: sldb-db
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - sldb-db:/var/lib/mysql
    restart: always
volumes:
  sldb-db:
  sldb-log:
